docker-build:
  stage: build
  script:
    - "curl -X POST -F token=0fc35482b4ca31b76ad4ee95587028 -F ref=master https://gitlab.com/api/v4/projects/18720527/trigger/pipeline"
  rules:
    - changes:
        - "**/*.py"
        - "**/*.ini"
        - "**/*.sh"
        - "**/*.yaml"
        - "**/*.docstring"


include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  rules:
    - changes:
        - "**/*.py"
        - "**/*.ini"
        - "**/*.sh"
